version: '3.2'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_HEAP_OPTS: -Xmx250M -Xms250M
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${EC2_IP_ADDRESS}:9092

  init_kafka:
    container_name: init_kafka
    image: confluentinc/cp-kafka:7.2.0
    depends_on:
      - kafka
    command: bash -c "
        kafka-topics --bootstrap-server ${EC2_IP_ADDRESS}:9092 --create --if-not-exists --topic ${KAFKA_TOPIC_COIN} --replication-factor 1 --partitions 1 &&
        kafka-topics --bootstrap-server ${EC2_IP_ADDRESS}:9092 --create --if-not-exists --topic ${KAFKA_TOPIC_STOCK} --replication-factor 1 --partitions 1"
